---
- name: Configure software
  hosts: localhost
  become: yes
  tasks:
    - name: Install packages
      package: name={{ item }} state=present
      with_items:
        - git
        - emacs24
        - network-manager-openvpn-gnome
    - name: Install Spacemacs
      git:
        repo: https://github.com/syl20bnr/spacemacs
        dest: ~/.emacs.d
        version: master
