---
- name: Configure software
  hosts: localhost
  become: yes
  tasks:
    - name: SBT repository key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823
    - name: SBT repository
      apt_repository:
        repo: "deb https://dl.bintray.com/sbt/debian /"
        state: present
    - name: Update packages
      apt: update_cache=yes
    - name: Install packages
      package: name={{ item }} state=present
      with_items:
        - chromium-browser
        - git
        - emacs24
        - network-manager-openvpn-gnome
        - openjdk-8-jdk
        - sbt
    - name: Install Spacemacs
      git:
        repo: https://github.com/syl20bnr/spacemacs
        dest: ~/.emacs.d
        version: master
